import VideoPlayer from "@/components/player/VideoPlayer";

export default function TestPlayerPage() {
  return (
    <main
      style={{
        minHeight: "100vh",
        padding: "40px",
        background: "#111",
        color: "white",
      }}
    >
      <h1>HLS Test Player</h1>

      <p>
        MPEG-TS HLS stream generated by FFmpeg.
      </p>

      <VideoPlayer
        src="/api/hls/test-720/master.m3u8"
      />
    </main>
  );
}